# Generated by Django 2.2.7 on 2021-04-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0002_auto_20210402_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentuser',
            name='qr',
        ),
        migrations.AddField(
            model_name='currentuser',
            name='door_id',
            field=models.IntegerField(null=True),
        ),
    ]
