# Generated by Django 2.2.7 on 2021-04-01 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0007_auto_20210402_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=200, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qr',
            name='user_id',
        ),
        migrations.AddField(
            model_name='qr',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_for_face.User'),
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='door',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_for_face.Door'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='door_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_for_face.Door'),
        ),
    ]
