# Generated by Django 2.2.7 on 2021-04-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0008_auto_20210402_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr',
            old_name='door_id',
            new_name='door',
        ),
    ]
