# Generated by Django 2.2.7 on 2021-04-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0009_auto_20210402_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentuser',
            old_name='user',
            new_name='my_user',
        ),
        migrations.RenameField(
            model_name='currentuser',
            old_name='door',
            new_name='user_door',
        ),
        migrations.RenameField(
            model_name='qr',
            old_name='user',
            new_name='current_user',
        ),
    ]
