# Generated by Django 2.2.7 on 2021-04-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0011_auto_20210402_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentuser',
            name='user',
        ),
        migrations.AddField(
            model_name='currentuser',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
