# Generated by Django 2.2.7 on 2021-04-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0014_auto_20210402_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
