# Generated by Django 2.2.7 on 2021-04-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0015_delete_currentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIndoors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='door',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='user',
        ),
        migrations.AddField(
            model_name='qr',
            name='door_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='qr_string',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
