# Generated by Django 2.2.7 on 2021-04-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0016_auto_20210421_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('В помещении', 'В помещении'), ('Вне помещении', 'Вне помещении')], default='Вне помещении', max_length=200, null=True),
        ),
    ]
