# Generated by Django 2.2.7 on 2021-04-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0017_auto_20210421_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIndoors',
            new_name='Inside',
        ),
    ]
