# Generated by Django 2.2.7 on 2021-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0019_auto_20210421_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
