# Generated by Django 2.2.7 on 2021-04-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0020_qr_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='door_id',
        ),
    ]
