# Generated by Django 2.2.7 on 2021-04-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0023_door_qr_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='status',
            field=models.CharField(choices=[('Открыто', 'Открыто'), ('Закрыто', 'Закрыто')], default='Закрыто', max_length=200, null=True),
        ),
    ]
