# Generated by Django 2.2.7 on 2021-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0024_door_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='door_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inside',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='manager',
            name='surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qr',
            name='qr_string',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
