# Generated by Django 2.2.7 on 2021-04-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0027_auto_20210426_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='inside',
            name='door_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inside',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='qr_string',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
