# Generated by Django 2.2.7 on 2021-04-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0028_auto_20210426_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='inside',
            name='name_surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
