# Generated by Django 2.2.7 on 2021-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0029_inside_name_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inside',
            old_name='name_surname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='inside',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
