# Generated by Django 2.2.7 on 2021-04-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0030_auto_20210427_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inside',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inside',
            name='surname',
        ),
    ]
