# Generated by Django 2.2.7 on 2021-04-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_for_face', '0031_auto_20210427_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
